---

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://database-1.cdsdyncjkfak.us-east-1.rds.amazonaws.com:5432/app
    username: postgres
    password: (i2~w%tnS2]kVhc51ooN6KWMJR|C
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}
...
